### ISSUE TITLE
Cannot read property 'targets' of undefined

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-compiler#17]
Packages affected:
- [`ws`](https://github.com/websockets/ws)
- [`usb`](https://github.com/nonolith/node-usb)
- [`ppps`](https://www.npmjs.com/package/ppps) (because of `usb`)

The compilation of  fails because of some pre-gyp errors:

```
vagrant up;
./compile.sh ws
downloading package...
total 12
drwxrwxr-x 3 vagrant vagrant 4096 Feb 16 17:11 .
drwxr-xr-x 3 vagrant root    4096 Feb 16 17:11 ..
drwxrwxr-x 2 vagrant vagrant 4096 Feb 16 17:11 build
Connection to 127.0.0.1 closed.
running build...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7731  100  7731    0     0  30657      0 --:--:-- --:--:-- --:--:-- 30678
=> nvm is already installed in /home/vagrant/.nvm, trying to update using git
=>
=> Source string already in /home/vagrant/.bashrc
=> Close and reopen your terminal to start using nvm
v4.2.1 is already installed.
Now using node v4.2.1 (npm v2.14.7)
Now using node v4.2.1 (npm v2.14.7)
/home/vagrant/.nvm/versions/node/v4.2.1/bin/pre-gypify -> /home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/pre-gypify/pre-gypify.js
npm WARN deprecated lodash.padleft@3.1.1: This package has been renamed. Use lodash.padstart@^4.0.0.
npm WARN deprecated lodash.padright@3.1.1: This package has been renamed. Use lodash.padend@^4.0.0.
/home/vagrant/.nvm/versions/node/v4.2.1/bin/node-gyp -> /home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/node-gyp/bin/node-gyp.js
/home/vagrant/.nvm/versions/node/v4.2.1/bin/node-pre-gyp -> /home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
pre-gypify@1.3.2 /home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/pre-gypify
├── gyp-reader@0.0.2
└── nomnom@1.8.1 (underscore@1.6.0, chalk@0.4.0)

node-gyp@3.3.0 /home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/node-gyp
├── graceful-fs@4.1.3
├── semver@5.1.0
├── osenv@0.1.3 (os-tmpdir@1.0.1, os-homedir@1.0.1)
├── nopt@3.0.6 (abbrev@1.0.7)
├── fstream@1.0.8 (inherits@2.0.1)
├── minimatch@1.0.0 (sigmund@1.0.1, lru-cache@2.7.3)
├── which@1.2.4 (isexe@1.1.2, is-absolute@0.1.7)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── tar@2.2.1 (inherits@2.0.1, block-stream@0.0.8)
├── npmlog@2.0.2 (ansi@0.3.1, are-we-there-yet@1.0.6, gauge@1.2.5)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@2.0.10)
├── rimraf@2.5.2 (glob@7.0.0)
├── request@2.69.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oauth-sign@0.8.1, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.1, node-uuid@1.4.7, qs@6.0.2, combined-stream@1.0.5, form-data@1.0.0-rc3, aws4@1.2.1, mime-types@2.1.10, bl@1.0.3, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
└── path-array@1.0.1 (array-index@1.0.0)

node-pre-gyp@0.6.21 /home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/node-pre-gyp
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.0
gyp info using node@4.2.1 | linux | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp http GET https://nodejs.org/dist/v4.2.1/node-v4.2.1-headers.tar.gz
gyp http 200 https://nodejs.org/dist/v4.2.1/node-v4.2.1-headers.tar.gz
gyp http GET https://nodejs.org/dist/v4.2.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/dist/v4.2.1/SHASUMS256.txt
4.2.1
gyp info ok
+ pre-gypify --package_name '{name}-{version}-{configuration}.tgz'
/home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/pre-gypify/pre-gypify.js:9
    var targetName = data.targets.filter(function (target) {
                         ^

TypeError: Cannot read property 'targets' of undefined
    at Immediate._onImmediate (/home/vagrant/.nvm/versions/node/v4.2.1/lib/node_modules/pre-gypify/pre-gypify.js:9:26)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
Connection to 127.0.0.1 closed.
```

**Comment by johnnyman727** [comment]
This also affects [`flocking`](https://www.npmjs.com/package/flocking).

**Comment by tcr** [comment]
Fixed in pre-gypify to warn about these.

`ws` is not a gyp module:

```
+ pre-gypify --package_name '{name}-{version}-{configuration}-{node_abi}-{platform}-{arch}.tgz'
binding.gyp does not exist.
Are you sure this is a binary node module?
Connection to 127.0.0.1 closed.
```

`usb` doesn't fail with this error:

```
+ pre-gypify --package_name '{name}-{version}-{configuration}-{node_abi}-{platform}-{arch}.tgz'
writing package.json...
kk
+ echo 'Release build'
Release build
+ node-pre-gyp rebuild --target_platform=linux --target_arch=mipsel --target=4.5.0
...
```

`ppps` is not a gyp module:

```
+ pre-gypify --package_name '{name}-{version}-{configuration}-{node_abi}-{platform}-{arch}.tgz'
binding.gyp does not exist.
Are you sure this is a binary node module?
Connection to 127.0.0.1 closed.
```

`flocking` is not a gyp module:

```
+ pre-gypify --package_name '{name}-{version}-{configuration}-{node_abi}-{platform}-{arch}.tgz'
binding.gyp does not exist.
Are you sure this is a binary node module?
Connection to 127.0.0.1 closed.
```

**Comment by johnnyman727** [comment]
Looks like `ws` made it's two binary modules opt-in since this issue was made. Also, both `bufferutil` and `utf-8-validate` compile properly. 

`usb` fails with the following error which is not related to this reported issue:

```
make: Entering directory '/root/build/package/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
```

`ppps` depends on USB and fails for the same reason

`flocking` does not depend on any binary modules either as far as I can tell. 

:+1:
